title: "WHXHW's Blog"
description: "C/C++ 개발일지 / 임베디드 공부중"
url: "https://youjewon.github.io"
author:
  name: "Je-won-Yu"
  email: "youjeawon03@gmail.com"
social:
  github: "https://github.com/youjewon"
